// Code generated by protoc-gen-go. DO NOT EDIT.
// source: holdem.proto

package holdem

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageType int32

const (
	MessageType_JOIN_GAME_REQUEST  MessageType = 0
	MessageType_JOIN_GAME_RESPONSE MessageType = 1
	MessageType_PLAYER_INFO_NOTIFY MessageType = 2
	MessageType_START_GAME_REQUEST MessageType = 3
	MessageType_SEND_CARD          MessageType = 4
	MessageType_BET_REQUEST        MessageType = 5
	MessageType_BET_NOTIFY         MessageType = 6
	MessageType_RESULT_NOTIFY      MessageType = 7
	MessageType_EXIT_GAME_REQUEST  MessageType = 8
	MessageType_EXIT_GAME_NOTIFY   MessageType = 9
	MessageType_ERROR              MessageType = 10
)

var MessageType_name = map[int32]string{
	0:  "JOIN_GAME_REQUEST",
	1:  "JOIN_GAME_RESPONSE",
	2:  "PLAYER_INFO_NOTIFY",
	3:  "START_GAME_REQUEST",
	4:  "SEND_CARD",
	5:  "BET_REQUEST",
	6:  "BET_NOTIFY",
	7:  "RESULT_NOTIFY",
	8:  "EXIT_GAME_REQUEST",
	9:  "EXIT_GAME_NOTIFY",
	10: "ERROR",
}

var MessageType_value = map[string]int32{
	"JOIN_GAME_REQUEST":  0,
	"JOIN_GAME_RESPONSE": 1,
	"PLAYER_INFO_NOTIFY": 2,
	"START_GAME_REQUEST": 3,
	"SEND_CARD":          4,
	"BET_REQUEST":        5,
	"BET_NOTIFY":         6,
	"RESULT_NOTIFY":      7,
	"EXIT_GAME_REQUEST":  8,
	"EXIT_GAME_NOTIFY":   9,
	"ERROR":              10,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eb97d04f7e2d4c62, []int{0}
}

type CardType int32

const (
	CardType_PLAYER CardType = 0
	CardType_FLOP   CardType = 1
	CardType_TURN   CardType = 2
	CardType_RIVER  CardType = 3
)

var CardType_name = map[int32]string{
	0: "PLAYER",
	1: "FLOP",
	2: "TURN",
	3: "RIVER",
}

var CardType_value = map[string]int32{
	"PLAYER": 0,
	"FLOP":   1,
	"TURN":   2,
	"RIVER":  3,
}

func (x CardType) String() string {
	return proto.EnumName(CardType_name, int32(x))
}

func (CardType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eb97d04f7e2d4c62, []int{1}
}

type PlayerRole int32

const (
	PlayerRole_ACTOR   PlayerRole = 0
	PlayerRole_WATCHER PlayerRole = 1
)

var PlayerRole_name = map[int32]string{
	0: "ACTOR",
	1: "WATCHER",
}

var PlayerRole_value = map[string]int32{
	"ACTOR":   0,
	"WATCHER": 1,
}

func (x PlayerRole) String() string {
	return proto.EnumName(PlayerRole_name, int32(x))
}

func (PlayerRole) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eb97d04f7e2d4c62, []int{2}
}

type GameRole int32

const (
	GameRole_DEALER GameRole = 0
	GameRole_SB     GameRole = 1
	GameRole_BB     GameRole = 2
	GameRole_UTG    GameRole = 3
	GameRole_NORMAL GameRole = 4
)

var GameRole_name = map[int32]string{
	0: "DEALER",
	1: "SB",
	2: "BB",
	3: "UTG",
	4: "NORMAL",
}

var GameRole_value = map[string]int32{
	"DEALER": 0,
	"SB":     1,
	"BB":     2,
	"UTG":    3,
	"NORMAL": 4,
}

func (x GameRole) String() string {
	return proto.EnumName(GameRole_name, int32(x))
}

func (GameRole) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eb97d04f7e2d4c62, []int{3}
}

type Header struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=holdem.MessageType" json:"type,omitempty"`
	Length               int32       `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	CheckSum             int32       `protobuf:"varint,3,opt,name=check_sum,json=checkSum,proto3" json:"check_sum,omitempty"`
	RoomId               int32       `protobuf:"varint,4,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb97d04f7e2d4c62, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_JOIN_GAME_REQUEST
}

func (m *Header) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Header) GetCheckSum() int32 {
	if m != nil {
		return m.CheckSum
	}
	return 0
}

func (m *Header) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

// join game request
type JoinGameRequest struct {
	PlayerId             int32      `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Role                 PlayerRole `protobuf:"varint,3,opt,name=role,proto3,enum=holdem.PlayerRole" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *JoinGameRequest) Reset()         { *m = JoinGameRequest{} }
func (m *JoinGameRequest) String() string { return proto.CompactTextString(m) }
func (*JoinGameRequest) ProtoMessage()    {}
func (*JoinGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb97d04f7e2d4c62, []int{1}
}

func (m *JoinGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinGameRequest.Unmarshal(m, b)
}
func (m *JoinGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinGameRequest.Marshal(b, m, deterministic)
}
func (m *JoinGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinGameRequest.Merge(m, src)
}
func (m *JoinGameRequest) XXX_Size() int {
	return xxx_messageInfo_JoinGameRequest.Size(m)
}
func (m *JoinGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinGameRequest proto.InternalMessageInfo

func (m *JoinGameRequest) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *JoinGameRequest) GetRole() PlayerRole {
	if m != nil {
		return m.Role
	}
	return PlayerRole_ACTOR
}

type Player struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Amount               int32    `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb97d04f7e2d4c62, []int{2}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Player) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Player) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *Player) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

// notify all related player before each round
type PlayerInfoNotify struct {
	Player               *Player    `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Role                 PlayerRole `protobuf:"varint,2,opt,name=role,proto3,enum=holdem.PlayerRole" json:"role,omitempty"`
	GameRole             GameRole   `protobuf:"varint,3,opt,name=game_role,json=gameRole,proto3,enum=holdem.GameRole" json:"game_role,omitempty"`
	Position             int32      `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PlayerInfoNotify) Reset()         { *m = PlayerInfoNotify{} }
func (m *PlayerInfoNotify) String() string { return proto.CompactTextString(m) }
func (*PlayerInfoNotify) ProtoMessage()    {}
func (*PlayerInfoNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb97d04f7e2d4c62, []int{3}
}

func (m *PlayerInfoNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfoNotify.Unmarshal(m, b)
}
func (m *PlayerInfoNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfoNotify.Marshal(b, m, deterministic)
}
func (m *PlayerInfoNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfoNotify.Merge(m, src)
}
func (m *PlayerInfoNotify) XXX_Size() int {
	return xxx_messageInfo_PlayerInfoNotify.Size(m)
}
func (m *PlayerInfoNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfoNotify.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfoNotify proto.InternalMessageInfo

func (m *PlayerInfoNotify) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *PlayerInfoNotify) GetRole() PlayerRole {
	if m != nil {
		return m.Role
	}
	return PlayerRole_ACTOR
}

func (m *PlayerInfoNotify) GetGameRole() GameRole {
	if m != nil {
		return m.GameRole
	}
	return GameRole_DEALER
}

func (m *PlayerInfoNotify) GetPosition() int32 {
	if m != nil {
		return m.Position
	}
	return 0
}

// reply all players in the same room
type JoinGameResponse struct {
	Players              []*PlayerInfoNotify `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *JoinGameResponse) Reset()         { *m = JoinGameResponse{} }
func (m *JoinGameResponse) String() string { return proto.CompactTextString(m) }
func (*JoinGameResponse) ProtoMessage()    {}
func (*JoinGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb97d04f7e2d4c62, []int{4}
}

func (m *JoinGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinGameResponse.Unmarshal(m, b)
}
func (m *JoinGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinGameResponse.Marshal(b, m, deterministic)
}
func (m *JoinGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinGameResponse.Merge(m, src)
}
func (m *JoinGameResponse) XXX_Size() int {
	return xxx_messageInfo_JoinGameResponse.Size(m)
}
func (m *JoinGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinGameResponse proto.InternalMessageInfo

func (m *JoinGameResponse) GetPlayers() []*PlayerInfoNotify {
	if m != nil {
		return m.Players
	}
	return nil
}

type StartGameRequest struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartGameRequest) Reset()         { *m = StartGameRequest{} }
func (m *StartGameRequest) String() string { return proto.CompactTextString(m) }
func (*StartGameRequest) ProtoMessage()    {}
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb97d04f7e2d4c62, []int{5}
}

func (m *StartGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartGameRequest.Unmarshal(m, b)
}
func (m *StartGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartGameRequest.Marshal(b, m, deterministic)
}
func (m *StartGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartGameRequest.Merge(m, src)
}
func (m *StartGameRequest) XXX_Size() int {
	return xxx_messageInfo_StartGameRequest.Size(m)
}
func (m *StartGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartGameRequest proto.InternalMessageInfo

func (m *StartGameRequest) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type SendCardNotify struct {
	CardType             CardType `protobuf:"varint,1,opt,name=card_type,json=cardType,proto3,enum=holdem.CardType" json:"card_type,omitempty"`
	Num                  int32    `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	Cards                []string `protobuf:"bytes,3,rep,name=cards,proto3" json:"cards,omitempty"`
	Receiver             string   `protobuf:"bytes,4,opt,name=receiver,proto3" json:"receiver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendCardNotify) Reset()         { *m = SendCardNotify{} }
func (m *SendCardNotify) String() string { return proto.CompactTextString(m) }
func (*SendCardNotify) ProtoMessage()    {}
func (*SendCardNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb97d04f7e2d4c62, []int{6}
}

func (m *SendCardNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendCardNotify.Unmarshal(m, b)
}
func (m *SendCardNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendCardNotify.Marshal(b, m, deterministic)
}
func (m *SendCardNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendCardNotify.Merge(m, src)
}
func (m *SendCardNotify) XXX_Size() int {
	return xxx_messageInfo_SendCardNotify.Size(m)
}
func (m *SendCardNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_SendCardNotify.DiscardUnknown(m)
}

var xxx_messageInfo_SendCardNotify proto.InternalMessageInfo

func (m *SendCardNotify) GetCardType() CardType {
	if m != nil {
		return m.CardType
	}
	return CardType_PLAYER
}

func (m *SendCardNotify) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *SendCardNotify) GetCards() []string {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *SendCardNotify) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

type BetRequest struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Amount               int32    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Check                bool     `protobuf:"varint,3,opt,name=check,proto3" json:"check,omitempty"`
	Drop                 bool     `protobuf:"varint,4,opt,name=drop,proto3" json:"drop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BetRequest) Reset()         { *m = BetRequest{} }
func (m *BetRequest) String() string { return proto.CompactTextString(m) }
func (*BetRequest) ProtoMessage()    {}
func (*BetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb97d04f7e2d4c62, []int{7}
}

func (m *BetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BetRequest.Unmarshal(m, b)
}
func (m *BetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BetRequest.Marshal(b, m, deterministic)
}
func (m *BetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BetRequest.Merge(m, src)
}
func (m *BetRequest) XXX_Size() int {
	return xxx_messageInfo_BetRequest.Size(m)
}
func (m *BetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BetRequest proto.InternalMessageInfo

func (m *BetRequest) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *BetRequest) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *BetRequest) GetCheck() bool {
	if m != nil {
		return m.Check
	}
	return false
}

func (m *BetRequest) GetDrop() bool {
	if m != nil {
		return m.Drop
	}
	return false
}

type Pot struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Amount               int32    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pot) Reset()         { *m = Pot{} }
func (m *Pot) String() string { return proto.CompactTextString(m) }
func (*Pot) ProtoMessage()    {}
func (*Pot) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb97d04f7e2d4c62, []int{8}
}

func (m *Pot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pot.Unmarshal(m, b)
}
func (m *Pot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pot.Marshal(b, m, deterministic)
}
func (m *Pot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pot.Merge(m, src)
}
func (m *Pot) XXX_Size() int {
	return xxx_messageInfo_Pot.Size(m)
}
func (m *Pot) XXX_DiscardUnknown() {
	xxx_messageInfo_Pot.DiscardUnknown(m)
}

var xxx_messageInfo_Pot proto.InternalMessageInfo

func (m *Pot) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *Pot) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type BetNotify struct {
	BetRequest           *BetRequest `protobuf:"bytes,1,opt,name=bet_request,json=betRequest,proto3" json:"bet_request,omitempty"`
	Pots                 []*Pot      `protobuf:"bytes,2,rep,name=pots,proto3" json:"pots,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BetNotify) Reset()         { *m = BetNotify{} }
func (m *BetNotify) String() string { return proto.CompactTextString(m) }
func (*BetNotify) ProtoMessage()    {}
func (*BetNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb97d04f7e2d4c62, []int{9}
}

func (m *BetNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BetNotify.Unmarshal(m, b)
}
func (m *BetNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BetNotify.Marshal(b, m, deterministic)
}
func (m *BetNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BetNotify.Merge(m, src)
}
func (m *BetNotify) XXX_Size() int {
	return xxx_messageInfo_BetNotify.Size(m)
}
func (m *BetNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_BetNotify.DiscardUnknown(m)
}

var xxx_messageInfo_BetNotify proto.InternalMessageInfo

func (m *BetNotify) GetBetRequest() *BetRequest {
	if m != nil {
		return m.BetRequest
	}
	return nil
}

func (m *BetNotify) GetPots() []*Pot {
	if m != nil {
		return m.Pots
	}
	return nil
}

type ResultNotify struct {
	ActivePlayers        []*ResultNotify_PlayerInfo `protobuf:"bytes,1,rep,name=active_players,json=activePlayers,proto3" json:"active_players,omitempty"`
	Pots                 []*Pot                     `protobuf:"bytes,2,rep,name=pots,proto3" json:"pots,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ResultNotify) Reset()         { *m = ResultNotify{} }
func (m *ResultNotify) String() string { return proto.CompactTextString(m) }
func (*ResultNotify) ProtoMessage()    {}
func (*ResultNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb97d04f7e2d4c62, []int{10}
}

func (m *ResultNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultNotify.Unmarshal(m, b)
}
func (m *ResultNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultNotify.Marshal(b, m, deterministic)
}
func (m *ResultNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultNotify.Merge(m, src)
}
func (m *ResultNotify) XXX_Size() int {
	return xxx_messageInfo_ResultNotify.Size(m)
}
func (m *ResultNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultNotify.DiscardUnknown(m)
}

var xxx_messageInfo_ResultNotify proto.InternalMessageInfo

func (m *ResultNotify) GetActivePlayers() []*ResultNotify_PlayerInfo {
	if m != nil {
		return m.ActivePlayers
	}
	return nil
}

func (m *ResultNotify) GetPots() []*Pot {
	if m != nil {
		return m.Pots
	}
	return nil
}

type ResultNotify_PlayerInfo struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Position             int32    `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	Amount               int32    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	IsWin                bool     `protobuf:"varint,4,opt,name=is_win,json=isWin,proto3" json:"is_win,omitempty"`
	Cards                []string `protobuf:"bytes,5,rep,name=cards,proto3" json:"cards,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultNotify_PlayerInfo) Reset()         { *m = ResultNotify_PlayerInfo{} }
func (m *ResultNotify_PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*ResultNotify_PlayerInfo) ProtoMessage()    {}
func (*ResultNotify_PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb97d04f7e2d4c62, []int{10, 0}
}

func (m *ResultNotify_PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultNotify_PlayerInfo.Unmarshal(m, b)
}
func (m *ResultNotify_PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultNotify_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *ResultNotify_PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultNotify_PlayerInfo.Merge(m, src)
}
func (m *ResultNotify_PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_ResultNotify_PlayerInfo.Size(m)
}
func (m *ResultNotify_PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultNotify_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResultNotify_PlayerInfo proto.InternalMessageInfo

func (m *ResultNotify_PlayerInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ResultNotify_PlayerInfo) GetPosition() int32 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *ResultNotify_PlayerInfo) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ResultNotify_PlayerInfo) GetIsWin() bool {
	if m != nil {
		return m.IsWin
	}
	return false
}

func (m *ResultNotify_PlayerInfo) GetCards() []string {
	if m != nil {
		return m.Cards
	}
	return nil
}

type ExitGameRequest struct {
	Player               *Player  `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExitGameRequest) Reset()         { *m = ExitGameRequest{} }
func (m *ExitGameRequest) String() string { return proto.CompactTextString(m) }
func (*ExitGameRequest) ProtoMessage()    {}
func (*ExitGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb97d04f7e2d4c62, []int{11}
}

func (m *ExitGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExitGameRequest.Unmarshal(m, b)
}
func (m *ExitGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExitGameRequest.Marshal(b, m, deterministic)
}
func (m *ExitGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExitGameRequest.Merge(m, src)
}
func (m *ExitGameRequest) XXX_Size() int {
	return xxx_messageInfo_ExitGameRequest.Size(m)
}
func (m *ExitGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExitGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExitGameRequest proto.InternalMessageInfo

func (m *ExitGameRequest) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type ExitGameNotify struct {
	Player               *Player  `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExitGameNotify) Reset()         { *m = ExitGameNotify{} }
func (m *ExitGameNotify) String() string { return proto.CompactTextString(m) }
func (*ExitGameNotify) ProtoMessage()    {}
func (*ExitGameNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb97d04f7e2d4c62, []int{12}
}

func (m *ExitGameNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExitGameNotify.Unmarshal(m, b)
}
func (m *ExitGameNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExitGameNotify.Marshal(b, m, deterministic)
}
func (m *ExitGameNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExitGameNotify.Merge(m, src)
}
func (m *ExitGameNotify) XXX_Size() int {
	return xxx_messageInfo_ExitGameNotify.Size(m)
}
func (m *ExitGameNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_ExitGameNotify.DiscardUnknown(m)
}

var xxx_messageInfo_ExitGameNotify proto.InternalMessageInfo

func (m *ExitGameNotify) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb97d04f7e2d4c62, []int{13}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("holdem.MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("holdem.CardType", CardType_name, CardType_value)
	proto.RegisterEnum("holdem.PlayerRole", PlayerRole_name, PlayerRole_value)
	proto.RegisterEnum("holdem.GameRole", GameRole_name, GameRole_value)
	proto.RegisterType((*Header)(nil), "holdem.Header")
	proto.RegisterType((*JoinGameRequest)(nil), "holdem.JoinGameRequest")
	proto.RegisterType((*Player)(nil), "holdem.Player")
	proto.RegisterType((*PlayerInfoNotify)(nil), "holdem.PlayerInfoNotify")
	proto.RegisterType((*JoinGameResponse)(nil), "holdem.JoinGameResponse")
	proto.RegisterType((*StartGameRequest)(nil), "holdem.StartGameRequest")
	proto.RegisterType((*SendCardNotify)(nil), "holdem.SendCardNotify")
	proto.RegisterType((*BetRequest)(nil), "holdem.BetRequest")
	proto.RegisterType((*Pot)(nil), "holdem.Pot")
	proto.RegisterType((*BetNotify)(nil), "holdem.BetNotify")
	proto.RegisterType((*ResultNotify)(nil), "holdem.ResultNotify")
	proto.RegisterType((*ResultNotify_PlayerInfo)(nil), "holdem.ResultNotify.PlayerInfo")
	proto.RegisterType((*ExitGameRequest)(nil), "holdem.ExitGameRequest")
	proto.RegisterType((*ExitGameNotify)(nil), "holdem.ExitGameNotify")
	proto.RegisterType((*Error)(nil), "holdem.Error")
}

func init() { proto.RegisterFile("holdem.proto", fileDescriptor_eb97d04f7e2d4c62) }

var fileDescriptor_eb97d04f7e2d4c62 = []byte{
	// 891 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x0e, 0x49, 0x91, 0x22, 0x47, 0xb1, 0xbc, 0xd9, 0x26, 0x29, 0x91, 0xa2, 0x88, 0x41, 0x14,
	0xa9, 0x61, 0x20, 0x29, 0xe0, 0x20, 0x40, 0x7f, 0x4e, 0x92, 0x4d, 0x39, 0x0a, 0x64, 0x49, 0x5d,
	0x52, 0x49, 0x73, 0x22, 0x68, 0x71, 0x63, 0x13, 0x16, 0xb9, 0xea, 0x92, 0x72, 0xeb, 0x53, 0x0f,
	0x39, 0xf5, 0x61, 0xfa, 0x5c, 0x7d, 0x8d, 0x62, 0x77, 0x49, 0x8a, 0x32, 0xd0, 0x36, 0xed, 0x49,
	0xf3, 0x3f, 0xf3, 0xed, 0x7c, 0x1c, 0xc1, 0xfd, 0x2b, 0xb6, 0x4a, 0x68, 0xf6, 0x62, 0xcd, 0x59,
	0xc9, 0xb0, 0xa5, 0x34, 0xef, 0x37, 0xb0, 0x5e, 0xd3, 0x38, 0xa1, 0x1c, 0x7f, 0x0d, 0x9d, 0xf2,
	0x76, 0x4d, 0x5d, 0xed, 0x40, 0x3b, 0xec, 0x1f, 0x7f, 0xf6, 0xa2, 0x0a, 0x3f, 0xa7, 0x45, 0x11,
	0x5f, 0xd2, 0xf0, 0x76, 0x4d, 0x89, 0x0c, 0xc0, 0x8f, 0xc1, 0x5a, 0xd1, 0xfc, 0xb2, 0xbc, 0x72,
	0xf5, 0x03, 0xed, 0xd0, 0x24, 0x95, 0x86, 0xbf, 0x00, 0x67, 0x79, 0x45, 0x97, 0xd7, 0x51, 0xb1,
	0xc9, 0x5c, 0x43, 0xba, 0x6c, 0x69, 0x08, 0x36, 0x19, 0xfe, 0x1c, 0xba, 0x9c, 0xb1, 0x2c, 0x4a,
	0x13, 0xb7, 0xa3, 0xb2, 0x84, 0x3a, 0x4e, 0xbc, 0xb7, 0xb0, 0xff, 0x86, 0xa5, 0xf9, 0x59, 0x9c,
	0x51, 0x42, 0x7f, 0xde, 0xd0, 0xa2, 0x14, 0x85, 0xd6, 0xab, 0xf8, 0x96, 0x72, 0x11, 0xad, 0x7a,
	0xd8, 0xca, 0x30, 0x4e, 0xf0, 0x33, 0xe8, 0x70, 0xb6, 0xa2, 0xb2, 0x41, 0xff, 0x18, 0xd7, 0x63,
	0xce, 0xa5, 0x9f, 0xb0, 0x15, 0x25, 0xd2, 0xef, 0x5d, 0x83, 0xa5, 0x6c, 0xb8, 0x0f, 0x7a, 0x9a,
	0x48, 0x58, 0x26, 0xd1, 0xd3, 0x04, 0x3f, 0x01, 0x7b, 0x53, 0x50, 0x9e, 0xc7, 0x19, 0x95, 0xd5,
	0x1d, 0xd2, 0xe8, 0xf8, 0x4b, 0x80, 0xf8, 0x26, 0x2e, 0x63, 0x1e, 0x6d, 0xf8, 0x4a, 0xf6, 0x70,
	0x88, 0xa3, 0x2c, 0x0b, 0xbe, 0x12, 0xd0, 0xe3, 0x8c, 0x6d, 0xf2, 0xb2, 0x06, 0xa1, 0x34, 0xef,
	0x0f, 0x0d, 0x90, 0xea, 0x36, 0xce, 0x3f, 0xb0, 0x29, 0x2b, 0xd3, 0x0f, 0xb7, 0xf8, 0x19, 0x58,
	0x6a, 0x6a, 0xd9, 0xbb, 0x77, 0xdc, 0xbf, 0x33, 0x6b, 0xe5, 0x6d, 0x10, 0xe9, 0xff, 0x8c, 0x08,
	0x3f, 0x07, 0xe7, 0x32, 0xce, 0x68, 0xd4, 0x82, 0x8f, 0xea, 0x60, 0xf9, 0x7c, 0x22, 0xd4, 0xbe,
	0xac, 0x24, 0x01, 0x73, 0xcd, 0x8a, 0xb4, 0x4c, 0x59, 0x5e, 0x4d, 0xdb, 0xe8, 0xde, 0x08, 0xd0,
	0xf6, 0xd1, 0x8b, 0x35, 0xcb, 0x0b, 0x8a, 0x8f, 0xa1, 0xab, 0x06, 0x2a, 0x5c, 0xed, 0xc0, 0x38,
	0xec, 0x1d, 0xbb, 0xbb, 0x93, 0x6c, 0x91, 0x91, 0x3a, 0xd0, 0xfb, 0x06, 0x50, 0x50, 0xc6, 0xbc,
	0xfc, 0xdb, 0xed, 0x69, 0xbb, 0xdb, 0xf3, 0x3e, 0x6a, 0xd0, 0x0f, 0x68, 0x9e, 0x9c, 0xc4, 0x3c,
	0xa9, 0x9e, 0xe9, 0x39, 0x38, 0xcb, 0x98, 0x27, 0x51, 0x8b, 0x7c, 0x0d, 0x2c, 0x11, 0x26, 0x99,
	0x67, 0x2f, 0x2b, 0x09, 0x23, 0x30, 0xf2, 0x4d, 0x56, 0xd1, 0x42, 0x88, 0xf8, 0x21, 0x98, 0xc2,
	0x5b, 0xb8, 0xc6, 0x81, 0x71, 0xe8, 0x10, 0xa5, 0x08, 0xf8, 0x9c, 0x2e, 0x69, 0x7a, 0x43, 0xb9,
	0x84, 0xef, 0x90, 0x46, 0xf7, 0xae, 0x01, 0x86, 0xb4, 0xfc, 0x94, 0x81, 0x5b, 0x1b, 0xd7, 0xdb,
	0x1b, 0x97, 0x4d, 0x05, 0xb7, 0xe5, 0x22, 0x6c, 0xa2, 0x14, 0x8c, 0xa1, 0x93, 0x70, 0xb6, 0x96,
	0x0d, 0x6d, 0x22, 0x65, 0xef, 0x7b, 0x30, 0xe6, 0xec, 0xff, 0x75, 0xf1, 0x62, 0x70, 0x86, 0xb4,
	0xac, 0x1e, 0xea, 0x25, 0xf4, 0x2e, 0x68, 0x19, 0x71, 0x35, 0x76, 0x45, 0xaa, 0x86, 0x2e, 0x5b,
	0x40, 0x04, 0x2e, 0xb6, 0xe0, 0x9e, 0x42, 0x67, 0xcd, 0xca, 0xc2, 0xd5, 0xe5, 0x4a, 0x7b, 0xcd,
	0x4a, 0x59, 0x49, 0xa4, 0xc3, 0xfb, 0xa8, 0xc3, 0x7d, 0x42, 0x8b, 0xcd, 0xaa, 0x6e, 0x33, 0x82,
	0x7e, 0xbc, 0x2c, 0xd3, 0x1b, 0x1a, 0xed, 0xd2, 0xe1, 0x69, 0x9d, 0xdb, 0x8e, 0x6e, 0x71, 0x83,
	0xec, 0xa9, 0x34, 0x65, 0x29, 0xfe, 0xb5, 0xf3, 0x93, 0xdf, 0x35, 0x80, 0x6d, 0xfa, 0xce, 0x67,
	0xa9, 0xdd, 0xf9, 0x2c, 0xdb, 0x5c, 0xd6, 0x77, 0xb9, 0xdc, 0x7a, 0x3b, 0x63, 0x67, 0x43, 0x8f,
	0xc0, 0x4a, 0x8b, 0xe8, 0x97, 0x34, 0xaf, 0xb6, 0x61, 0xa6, 0xc5, 0xbb, 0x34, 0xdf, 0xb2, 0xc5,
	0x6c, 0xb1, 0xc5, 0xfb, 0x0e, 0xf6, 0xfd, 0x5f, 0xd3, 0x1d, 0x1e, 0x7f, 0xe2, 0xe7, 0xeb, 0x7d,
	0x0b, 0xfd, 0x3a, 0xf5, 0xbf, 0x7d, 0xf8, 0xde, 0x2b, 0x30, 0x7d, 0xce, 0x19, 0x17, 0xb4, 0x59,
	0xb2, 0x84, 0x56, 0xb4, 0x90, 0x32, 0x76, 0xa1, 0x9b, 0xa9, 0xd3, 0x5b, 0x1d, 0xa9, 0x5a, 0x3d,
	0xfa, 0x53, 0x83, 0x5e, 0xeb, 0x2a, 0xe3, 0x47, 0xf0, 0xe0, 0xcd, 0x6c, 0x3c, 0x8d, 0xce, 0x06,
	0xe7, 0x7e, 0x44, 0xfc, 0x1f, 0x17, 0x7e, 0x10, 0xa2, 0x7b, 0xf8, 0x31, 0xe0, 0xb6, 0x39, 0x98,
	0xcf, 0xa6, 0x81, 0x8f, 0x34, 0x61, 0x9f, 0x4f, 0x06, 0xef, 0x7d, 0x12, 0x8d, 0xa7, 0xa3, 0x59,
	0x34, 0x9d, 0x85, 0xe3, 0xd1, 0x7b, 0xa4, 0x0b, 0x7b, 0x10, 0x0e, 0x48, 0xb8, 0x5b, 0xc7, 0xc0,
	0x7b, 0xe0, 0x04, 0xfe, 0xf4, 0x34, 0x3a, 0x19, 0x90, 0x53, 0xd4, 0xc1, 0xfb, 0xd0, 0x1b, 0xfa,
	0x61, 0xe3, 0x37, 0x71, 0x1f, 0x40, 0x18, 0xaa, 0x3a, 0x16, 0x7e, 0x00, 0x7b, 0xc4, 0x0f, 0x16,
	0x93, 0xc6, 0xd4, 0x15, 0x13, 0xfa, 0x3f, 0x8d, 0xef, 0x54, 0xb6, 0xf1, 0x43, 0x40, 0x5b, 0x73,
	0x15, 0xec, 0x60, 0x07, 0x4c, 0x9f, 0x90, 0x19, 0x41, 0x70, 0xf4, 0x0a, 0xec, 0xfa, 0x02, 0x60,
	0x00, 0x4b, 0x8d, 0x8d, 0xee, 0x61, 0x1b, 0x3a, 0xa3, 0xc9, 0x6c, 0x8e, 0x34, 0x21, 0x85, 0x0b,
	0x32, 0x45, 0xba, 0x48, 0x23, 0xe3, 0xb7, 0x3e, 0x41, 0xc6, 0xd1, 0x57, 0x35, 0xaf, 0xe4, 0x1d,
	0x74, 0xc0, 0x1c, 0x9c, 0x84, 0x33, 0x91, 0xd7, 0x83, 0xee, 0xbb, 0x41, 0x78, 0xf2, 0xda, 0x27,
	0x48, 0x3b, 0xfa, 0x01, 0xec, 0xfa, 0x6a, 0x8a, 0xe2, 0xa7, 0xfe, 0x60, 0x22, 0x8b, 0x5b, 0xa0,
	0x07, 0x43, 0xa4, 0x89, 0xdf, 0xe1, 0x10, 0xe9, 0xb8, 0x0b, 0xc6, 0x22, 0x3c, 0x43, 0x86, 0x08,
	0x9a, 0xce, 0xc8, 0xf9, 0x60, 0x82, 0x3a, 0x17, 0x96, 0xfc, 0x17, 0x7d, 0xf9, 0x57, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x36, 0xc7, 0xb6, 0x34, 0x55, 0x07, 0x00, 0x00,
}
